### ISSUE TITLE
将“使能”换成更加常用的词语

### ISSUE THREAD

**Issue by ShuiHuo** [loongson-community/areweloongyet#101]
“使能”这个词不知道别人看到是怎么想的，但我看了几次这个词都没能直接理解是什么意思，总感觉后面应该还有什么，但又没写出来，所以希望作者能将这个词换成更加适合当时场景的词语（开启、运行、启用等等）。

**Comment by jiegec** [comment]
“使能”是常见的硬件术语，意思就相当于 enable

**Comment by ShuiHuo** [comment]
完全可以换成更加易于理解的词，没必要用这种逐个字母翻译的词。
