### ISSUE TITLE
支持用户开关儿化标记 or 去除行文中的儿化标记

### ISSUE THREAD

**Issue by xen0n** [loongson-community/areweloongyet#113]
先前在群聊中，有吴语使用者表示其方言的儿化规则与北方方言不同，建议不在站点的内容中显式展示儿化标记。

鉴于本站（本人）一贯视多样性、平等参与这两件事，高于内容创作者的个性表达，个人认为：

* 要么支持标记不同的儿化规则，并支持配置；
* 要么支持开关儿化标记；
* 要么彻底删除所有儿化标记。

前两种选择将涉及开发量。如果选择这两项，预计应模仿 Docusaurus 对暗色模式的处理方法，可能涉及 swizzle 那个组件（加入一个开关儿化的图标 or 一个让用户选择习惯的儿化规则的模态框）。

**Comment by xry111** [comment]
要是我我就直接选 3 :)

**Comment by MingcongBai** [comment]
我也会直接选 3 —— 虽然理解属于个性表达，但这种个性表达的地域局限性很强，也可能会造成阅读困难

**Comment by OriginCode** [comment]
吳語兒化/兒綴規則普遍只給名詞作兒化，可參考 https://forum.wordreference.com/threads/%E5%90%B3%E8%AA%9E%E5%85%92%E5%8C%96%E9%9F%B3-nasal-coloring-in-wu.2819764/

我建議 3，考慮到各地兒化/兒綴規則不同，且粵語之類幾乎沒有兒化/兒綴的習慣。

**Comment by xen0n** [comment]
> 吳語兒化/兒綴規則普遍只給名詞作兒化/兒綴，可參考 https://forum.wordreference.com/threads/%E5%90%B3%E8%AA%9E%E5%85%92%E5%8C%96%E9%9F%B3-nasal-coloring-in-wu.2819764/
> 
> 我建議 3，考慮到各地兒化/兒綴規則不同，且粵語之類幾乎沒有兒化/兒綴的習慣。

感谢提供阅读材料！

看上去吴语的“儿化”现象只是小格（diminutive）形态标记，和官话儿化的多样语法功能不相关。这样说来本站对儿化的使用确实损害了表达多样性。

下一期《每周一龙》发布时会同步移除所有其他非必要的儿化标记，并修订《自然语言风格指南》。再次感谢您的建议！
