### ISSUE TITLE
补充 FibJS 适配情况

### ISSUE THREAD

**Issue by PinelliaC** [loongson-community/areweloongyet#127]
## 项目地址
https://github.com/fibjs/fibjs

### 官网
https://fibjs.org/
### wiki 地址
https://zh.wikipedia.org/zh-cn/Fibjs

## 编译环境截图

LoongArch64 真机

<img width="1195" alt="image" src="https://github.com/loongson-community/areweloongyet/assets/35207295/2b948650-6cae-43cd-8f06-d2924e47c46e">

## 成功编译结果截图

<img width="1189" alt="image" src="https://github.com/loongson-community/areweloongyet/assets/35207295/cc99ece5-dc1a-44a5-b16b-4771f9242d08">

## 测试用例运行截图

<img width="1196" alt="image" src="https://github.com/loongson-community/areweloongyet/assets/35207295/85da9676-ad15-419d-add5-3a3bf3eddac8">

**Comment by xen0n** [comment]
* Loongnix 不是新世界。您有在新世界发行版上试过吗？
* 上游未见适配代码或 PR，这工作是您做的吗？如果是的话，PR 或者提交地址在哪？

**Comment by PinelliaC** [comment]
感谢
- 目前仅在 Loongnix 上试运行过，未在其他版本试运行
- 我目前是 fibjs 的 contributors 之一，适配工作并不是我做的，具体提交记录见：
https://github.com/search?q=repo%3Afibjs%2Ffibjs+loongarch64&type=commits
https://github.com/search?q=repo%3Afibjs%2Ffibjs+loong64&type=commits
https://github.com/search?q=repo%3Afibjs%2Ffibjs_vender+loong64&type=commits

此外我们还制作了对应的 Qemu 的 dockerfile，用于 Github CI ，见：
https://github.com/fibjs/fibjs/blob/dev/dockerfiles/linux-build-env.loong64

**Comment by xry111** [comment]
我大概看了一下应该没有涉及新旧世界兼容性问题的地方 (除了 CI)，但是在本站宣布之前最少得用新世界测一下。

另外最好有人去上游交个 PR 把 CI 换成新世界的 (或者加一个新世界的)。

**Comment by PinelliaC** [comment]
好的，我们正在着手做新世界的适配工作，CI 的工作可能要稍等几天

**Comment by xen0n** [comment]
#128 is merged, so this is already done.
