### ISSUE TITLE
distro: Announce Linux From Scratch for LoongArch

### ISSUE THREAD

**Issue by xry111** [loongson-community/areweloongyet#25]
- 仓库：https://git.linuxfromscratch.org/lfs.git (分支 xry111/loongarch)
  - 由于 LFS 开发团队时间和精力有限，目前没有在主分支 (trunk) 支持任何非 x86/x86_64 架构的想法，所以将作为单独分支长期存在
  - 软件包更新将通过 merge 主分支进行
- 某种 gitweb 类似物：https://wiki.linuxfromscratch.org/lfs/browser/?rev=xry111/loongarch
- 生成好的手册：https://www.linuxfromscratch.org/~xry111/lfs/view/loongarch-systemd/

TODO:

- [x] 自动化测试 (已用 jhalfs 测试)
- [x] 测试和修复 SysVinit 版本 (https://www.linuxfromscratch.org/~xry111/lfs/view/loongarch/ <del>目前大概率不能用</del> 竟然直接就能用)
- [x] 中文翻译

**Comment by xry111** [comment]
大概施工了一个我的 LFS branch 的主页：https://www.linuxfromscratch.org/~xry111/lfs/

因为不会写 CSS 所以很丑

**Comment by xen0n** [comment]
Feel free to PR your additions directly to the repo!

**Comment by xry111** [comment]
> Feel free to PR your additions directly to the repo!

我还在想办法把中文翻译整合到 [xry111/lfs-book-i18n](/xry111/lfs-book-i18n) 中，因为直接开个 branch 似乎不是最好的办法。等折腾完再发……
