### ISSUE TITLE
Rust target 已经变更

### ISSUE THREAD

**Issue by Rabenda** [loongson-community/areweloongyet#40]
https://github.com/loongson-community/areweloongyet/blob/e3460a89b6995287051f3fefbe4b36a504f55a98/docs/loong-or-loongarch.md?plain=1#L115

**Comment by MariaBombardier** [comment]
这个不应该投稿到隔壁的[「长期」《每周一龙》/This Week in LoongArch 新闻线索信箱 #16](https://github.com/loongson-community/areweloongyet/issues/16)么？

**Comment by Rabenda** [comment]
> 这个不应该投稿到隔壁的[「长期」《每周一龙》/This Week in LoongArch 新闻线索信箱 #16](https://github.com/loongson-community/areweloongyet/issues/16)么？

不应该 现阶段单纯写错
