### ISSUE TITLE
RSS 推送 pubDate 字段内容与实际推送时间不符

### ISSUE THREAD

**Issue by weilinfox** [loongson-community/areweloongyet#48]
## 问题描述

XML 中的时间和实际推送时间不符，时间固定为 GMT 当日零时

```
<title>每周一龙：第 11 期</title>
<link>
https://areweloongyet.com/newsletter/this-week-in-loongarch-11
</link>
<guid>
https://areweloongyet.com/newsletter/this-week-in-loongarch-11
</guid>
<pubDate>Mon, 31 Jul 2023 00:00:00 GMT</pubDate>
```

## 预期结果

``pubDate`` 与实际时间基本一致

**Comment by xen0n** [comment]
似乎可通过往 frontmatter 加额外一个更精确的 `date` 字段实现：[Docusaurus doc](https://docusaurus.io/docs/blog#blog-post-date)，下期《每周一龙》尝试

**Comment by xen0n** [comment]
这个问题应该在 `/newsletter` 实例下已经全面修复了，确认下自己 close 了？@weilinfox

**Comment by xen0n** [comment]
或者我先 close 掉，后续有不预期再开新 issue 链接过来

**Comment by weilinfox** [comment]
好哦，感谢～
