### ISSUE TITLE
请求：细化Linux支持细节

### ISSUE THREAD

**Issue by zhangn1985** [loongson-community/areweloongyet#51]
Linux上游已经支持了LoongArch但是CPU及桥片的支持细节还不清楚。

能否整理出一张类似于下面网页的表格？
https://linux-sunxi.org/Linux_mainlining_effort#Status_Matrix

**Comment by xen0n** [comment]
不好意思刚看到，这个可以搞，我觉得目前在 `docs` 目录下边搞个 Markdown 表格就行了。要不你来折腾一个？

**Comment by xen0n** [comment]
我简单设想一下：表格的行是功能，列是 CPU/板卡组合等，单元格是以下几种：

* 某个版本号：从该版本开始有支持
* WIP：有人在搞了（消息有出处则链接到相应网页）
* TODO：已知硬件有此功能支持但功能没人搞
* N/A：硬件无此功能支持

**Comment by jiegec** [comment]
简单整理了一下：

CPU：

- SMT: [6.5](https://github.com/torvalds/linux/commit/f6f0c9a74a48448583c3cb0f3f067bc3fe0f13c6)
- LSX/LASX: [6.5](https://github.com/torvalds/linux/commit/616500232e632dba8b03981eeccadacf2fbf1c30)
- CRC32 加速: [6.4](https://github.com/torvalds/linux/commit/2f1648220214d18168e55920c21014e71c2d5bbc)

桥片：

- RTC(LOON0001): RTC_DRV_LOONGSON [6.5](https://github.com/torvalds/linux/commit/1b733a9ebc3d8011ca66ec6ff17f55a440358794)
- GPIO(LOON0002): GPIO_LOONGSON_64BIT [6.4](https://github.com/torvalds/linux/commit/7944d3b7fe86067509751473aa917fdfd662d92c)
- I2C(LOON0004): I2C_LS2X [6.3](https://github.com/torvalds/linux/commit/015e61f0bffd46600496e50d3b2298f51f6b11a8)
- GNET(0014:7a13): patches available
- EHCI(0014:7a14): ok
- OHCI(0014:7a24): ok
- XHCI(0014:7a34): ok
- GPU(0014:7a25): ?
- Display Controller(0014:7a36): patches available
- HD-Audio(0014:7a07): patches available
- SATA(0014:7a18): ok
- PCIE(0014:7a39/0014:7a49/0014:7159/0014:7169): ok
- SPI(0014:7a1b): patches available
- LPC(0014:7a0c): ?
