### ISSUE TITLE
版本号可读性不佳

### ISSUE THREAD

**Issue by Naville** [loongson-community/areweloongyet#57]
<img width="273" alt="image" src="https://github.com/loongson-community/areweloongyet/assets/5205699/6888223b-539e-4bdb-887e-8b0dd95b2a9f">
<img width="315" alt="image" src="https://github.com/loongson-community/areweloongyet/assets/5205699/a3084ef1-afc1-4790-a705-8b5f46bed0cf">

建议增加对比度

**Comment by xen0n** [comment]
您指的是仅淡色主题下的版本号对比度不高吗？还是两种主题都不够清晰？

目前这些版本号的透明度弄成较高，是故意的，因为这不是主要信息：预期会关注这些信息的人，基本都是各大发行版的打包人、维护者等，做新世界系统的这些同学对「追新」是有共识的——默认大家都会在，或者很快就会在最新版本，因此第一眼看过去只要能看清每个软件包的「最新正式版」支持状态就好了。而这部分信息已经由 emoji 传达了 ;-)

假设您是没有能力影响、修改您所用系统的最终用户，关注这里的版本号应该没有实际意义：这些软件大多数是如此底层，如果您本身没有在打包，或者能够影响您所用系统的打包者们使他们帮您打包，那么这些软件的版本应该是不容易随意改变（而不造成破坏）的。

这样有没有清晰一点？

**Comment by Naville** [comment]
感谢解释, 这样非常合理了:)
