### ISSUE TITLE
在 27 寸 4k 200% 屏幕下，网页字号过大

### ISSUE THREAD

**Issue by eatradish** [loongson-community/areweloongyet#74]
如图：

![图片](https://github.com/loongson-community/areweloongyet/assets/19554922/46ed3694-15f4-46a2-8944-6fbe6c9a1f3a)

**Comment by MingcongBai** [comment]
12.5 寸笔记本，1920x1200 分辨率，150% 缩放（即 1280x800 逻辑分辨率）

![图片](https://github.com/loongson-community/areweloongyet/assets/5006263/44a152fa-f824-4368-9c41-e7bb27e15295)

**Comment by xry111** [comment]
我在 4k 200% 和 1080p 100% 之间来回拖动没有发现不同。

是不是单纯就是字号太大了？

**Comment by eatradish** [comment]
> 我在 4k 200% 和 1080p 100% 之间来回拖动没有发现不同。
> 
> 是不是单纯就是字号太大了？

应该是的

**Comment by xry111** [comment]
好像已经改小了，如果没问题就 close 罢。

**Comment by xen0n** [comment]
是的：这个前一阵在写内容时候顺带改了一些。如果目前的页面展示效果符合预期了，麻烦顺手帮我 close 了 ;-)

**Comment by xen0n** [comment]
或者我先 close 掉，后续有不预期再开新 issue 链接过来
