### ISSUE TITLE
需求：加速中国大陆访问

### ISSUE THREAD

**Issue by xen0n** [loongson-community/areweloongyet#79]
随着读者群体增长，有许多主要来自非技术人员群体的新读者不熟练科学上网相关操作，或基于意识形态原因而不支持从境外 serve 网站内容。因此有必要考虑加速中国大陆地区的访问。

为此需要：

* [x] 为 `areweloongyet.com` 取得中国大陆备案 -- 进行中
* [x] 在网站 footer 添加备案信息 -- #80
* [x] 变更 GitHub Pages CNAME 配置，变为源站域名 -- #86
* [x] 配置~~国内~~全球加速 CDN 服务（钱暂时我自己出，后续要考虑透明化运营：运营数据披露等）
* [x] 确保境外请求性能不受劣化（预计本站有相当一部分用户群体不位于境内，如留学生等） -- 待观察

考虑到假如源站域名维持 `areweloongyet.com` 但中国大陆不 CNAME 到源站（因为需要加速），会导致位于中国大陆的 CDN 节点无法正常回源（因为会回到自己），双线解析可能不可行。

**Comment by xen0n** [comment]
或，研究 Gitee Pages 的可行性：但 Gitee Pages 目前并未向免费用户开放，Gitee 企业版很贵。

预计应该先跑前一种方案（GitHub Pages + 国内 CDN）几个月，看看成本，再做决定。目前猜 Gitee 方案大概没竞争力。

**Comment by xen0n** [comment]
开始操作 `areweloongyet.com` 的备案，预期挂在我个人主体的备案号下。

**Comment by xen0n** [comment]
Progress update:

* `areweloongyet.com` 备案手续已进行至最终步骤「管局审核」，预计 2 周左右可以成功，预期不会被刁难。取得备案后可马上配置 CDN 与网站 footer
* 双线解析方案调研：阿里云、DNSPod（数年前已被腾讯云收购）的多线解析功能均需开通收费套餐。目前解析服务用的 DNSPod，正在对比阿里云方案

**Comment by xen0n** [comment]
除多线解析外，也可配置 CDN 为全球加速，这样可以避免在 DNS 一侧购买付费套餐，但对于海外访问则无法利用 GitHub Pages 本身的免费 CDN 了。可能需要后续测算下成本方面影响。

中国大陆境内各大 CDN 提供商 HTTPS 加速服务定价调研（2023.10.21 数据；价格单位 CNY/GB）：

|提供商|中国大陆|备注|
|------|------|----|
|七牛云|<ul><li>0.28（后付费）</li><li>0.21（资源包）</li></ul>|[官网定价页面](https://www.qiniu.com/prices/qcdn)|
|华为云|TBD|TBD|
|阿里云|TBD|TBD|
|腾讯云|TBD|TBD|
|京东云|TBD|TBD|

**Comment by xen0n** [comment]
DNS 解析套餐：

* [DNSPod](https://buy.dnspod.cn/dns)：99 CNY/年
* 阿里云：40.8 CNY/年

此套餐价格均不包括「DNS 安全防护」服务（默认开启此增值服务，则手工关闭后再看价格）

**Comment by xen0n** [comment]
提前将 `areweloongyet.com` 的 NS 记录切回阿里云（万网）

**Comment by xen0n** [comment]
ICP 备案手续完成，CDN 相关配置完成，待进行公安备案

**Comment by xen0n** [comment]
因为 issue 标题的需求已经实现，先关掉，不影响后续进度同步

**Comment by akatsukiro** [comment]
是否可以尝试将 Vercel 用作境外内容分发？Vercel 对接 Github 是很方便的，且个人开发者每月拥有 100G 的 CDN 流量。

另，海外应当可以直接解析到 Github Pages 的吧，（如果担心海外访问的话，）为什么现在没有这样做呢？看到您提及了 `多线解析` ，这对于海内外分线路解析来说其实是用不到的，或许是我错误判断了您的需求？希望能得到您的解答。

说到 DNS ，其实您可以尝试 华为云 DNS ，它目前免费，且各项功能齐全。

最后，感谢您的贡献。

**Comment by xen0n** [comment]
@akatsukiro 

> 是否可以尝试将 Vercel 用作境外内容分发？

用不着，因为不做任何额外配置的 GitHub Pages 本身就是背靠有着全球线路的 Fastly CDN

> 海外应当可以直接解析到 Github Pages 的吧，为什么现在没有这样做呢？

目前我使用的 DNS 解析服务（DNSPod 或阿里云 DNS），其根据来访者 IP 而返回不同结果的功能（即所谓“多线解析”）都是付费功能。我目前没开相应的套餐，所以无法使用。

> 说到 DNS ，其实您可以尝试 华为云 DNS ，它目前免费，且各项功能齐全。

目前这个网站的运维并没脱离我的个人运维 workflow，所以可能我个人不会去引入这第三个供应商；不过我会调研的，感谢您的建议。

> 最后，感谢您的贡献。

;-)

**Comment by akatsukiro** [comment]
> 目前我使用的 DNS 解析服务（DNSPod 或阿里云 DNS），其根据来访者 IP 而返回不同结果的功能（即所谓“多线解析”）都是付费功能。

如果您的需求仅仅是 `根据来访者 IP 而返回不同结果` ，那只需添加多个解析，并指定其解析线路即可。这个功能以前 DNSPod 是免费的，但现在似乎没法指定境外了；而
阿里云 
![image](https://github.com/loongson-community/areweloongyet/assets/69096852/9d05425c-2eb4-4362-bca8-ab2356f85be2)
华为云
![image](https://github.com/loongson-community/areweloongyet/assets/69096852/a2a1e305-d42d-4b5a-b0e1-945cdad078ba)
均可免费使用并正常解析，其中华为云更是可以精确到省、市。
所以这可能是一个抉择。

**Comment by xen0n** [comment]
@akatsukiro 感谢您的提醒，我重新阅读了阿里云 DNS 的记录配置页面，它的收费套餐是支持细化到运营商/国家级别，而单纯的“境外”线路是免费套餐即支持的。

目前我将 `areweloongyet.com` 的 NS 记录指向阿里云了，并将境外请求解析到了 GitHub Pages 源站（Fastly）。我这里测试通过，如果有问题的话可以再开 issue。

再次感谢您的建议！
